#etcetera_folder_name: "disfinder"
local_bashrc_file: ".bashrc"
user_home_dir: "~{{ ansible_ssh_user }}"
#local_bash_profile: ".bash_profile"


include:
  comments: true
  common_ubuntu: true
  common: true
  bindings: true
  color: true
  alias:
    common: true
    develop: true
  completion: true
  path:
    develop: true
  ps1: true


ps1:
  developer: true
  color_root: true
  gray_user: false
  color_user: false
  color_user_multiline: true


################# Screen
local_screenrc_file: ".screenrc"
