---
- name: "SSH config filename is:"
  debug:
    var=local_ssh_config_file
  tags:
    - debug

- name: Fill local ssh config file
  tags:
    - ssh_config
  template:
    src=ssh_config
    dest={{ ssh_config_dest_dir }}/{{ local_ssh_config_file }}
    mode=0644
